# Site settings
title: Professional Button Pusher. Rocketman. Sometimes, Philosopher.
author_name: Rob Mills
email: hi@robgmills.com
description: > # this means to ignore newlines until "baseurl:"
  The mental dump of a passionate, deep thinking software engineer who's
  got a bit of an adventurous side.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://robgmills.com" # the base hostname & protocol for your site
twitter_username: robgmills
github_username:  robgmills
linkedin_username: robgmills

paginate: 5
paginate_path: "/blog/page/:num/"

# Build settings
markdown: redcarpet

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript","tables", "with_toc_data"]

# Gems
gems:
- jekyll-sitemap
- jekyll-redirect-from
- jekyll-mentions
- jemoji
- jekyll-feed