# Site settings
title: Professional Button Pusher. Rocketman. Sometimes, Philosopher.
author_name: Rob Mills
email: hi@robgmills.com
description: > # this means to ignore newlines until "baseurl:"
  The mental dump of a passionate, deep thinking software engineer who&39;s
  got a bit of an adventurous side.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://robgmills.com" # the base hostname & protocol for your site
enforce_ssl: robgmills.com
user: robgmills

paginate: 10
paginate_path: "/blog/page/:num/"

# Build settings
# Synonomous with gh-pages settings: https://help.github.com/articles/using-jekyll-with-pages/#configuring-jekyll
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false
  math_engine: mathjax 

plugins:
- jekyll-coffeescript
- jekyll-paginate
- jekyll-sitemap
- jekyll-redirect-from
- jekyll-feed
